version: '3'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80"
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/app
    depends_on:
      - mariadb
  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./:/app
      - vol-composer:/root/.composer/cache
    depends_on:
      - mariadb
    tty: true
  mariadb:
    image: mariadb:10.10
    restart: 'always'
    environment:
      - MYSQL_ROOT_PASSWORD=magxuT0ifPhLb7BT
      - MYSQL_DATABASE=analytics_viewer
      - MYSQL_USER=analytics_viewer
      - MYSQL_PASSWORD=EHBNNoMIQOj2r2Fy
    ports:
      - "33061:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  node:
    image: node:19-alpine
    volumes:
      - ./:/app
    working_dir: /app
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

volumes:
  vol-composer:
